const data = [
    {
        NAME: 'BÀI TẬP HÓA ĐẠI CƯƠNG',
        SL1: '80',
        SL2: '70',
        G: ' 32,000',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C1',
    },
    {
        NAME: 'TOÁN CAO CẤP TẬP 1',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C1',
    },
    {
        NAME: 'RÈN LUYỆN KỸ NĂNG THỰC HÀNH TIẾNG VIỆT',
        SL1: '75',
        SL2: '65',
        G: ' 42,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C2',
    },
    {
        NAME: 'GT VĂN HỌC SO SÁNH',
        SL1: '26',
        SL2: '16',
        G: ' 70,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C2',
    },
    {
        NAME: 'DẪN LUẬN NGÔN NGỮ HỌC',
        SL1: '65',
        G: ' 60,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C2',
    },
    {
        NAME: 'CƠ SỞ SINH THÁI HỌC',
        SL1: '46',
        SL2: '34',
        G: ' 80,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C3',
    },
    {
        NAME: 'GIÁO TRÌNH PHÁP LUẬT',
        SL1: '90',
        G: ' 21,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C3',
    },
    {
        NAME: 'VIRUT HỌC',
        SL1: '28',
        G: ' 80,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C4',
    },
    {
        NAME: 'LỊCH SỬ THẾ GIỚI CỔ ĐẠI',
        SL1: '50',
        SL2: '42',
        G: ' 70,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C4',
    },
    {
        NAME: 'TUYẾN ĐIỂM DU LỊCH VIỆT NAM',
        SL1: '24',
        G: ' 120,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C4',
    },
    {
        NAME: 'NGỮ PHÁP VIỆT NAM',
        SL1: '34',
        SL2: '26',
        G: ' 80,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C5',
    },
    {
        NAME: 'VĂN BẢN VÀ LK TIẾNG VIỆT',
        G: ' 40,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C5',
    },
    {
        NAME: 'HỆ THỐNG LIÊN KẾT VĂN BẢN TIẾNG VIỆT',
        SL1: '62',
        G: ' 40,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C5',
    },
    {
        NAME: 'PHƯƠNG PHÁP DẠY HỌC TIẾNG VIỆT',
        SL1: '70',
        SL2: '37',
        G: ' 32,000 ',
        VT1: 'KH',
        VT2: 'D1',
        VT3: 'TH',
        VT4: 'C5',
    },
]

export default data
